namespace CursedBroom.Aseprite.Tests {
    enum TestAsset {
        PortraitsWithTags_Aseprite,
        PortraitsWithTags_Sheet,
        PortraitsWithTags_Data,
        Icon_Aseprite,
        Icon_Sheet,
        Icon_Data,
        Avatar_Data,
        SpiderWeb_Aseprite,
        SpiderWeb_Sheet,
        SpiderWeb_Data,
        PortraitsWithSlices_Aseprite,
        PortraitsWithSlices_Sheet,
        PortraitsWithSlices_Data,
        SlicedDoor_Aseprite,
        PortraitsWithSlicesAndTags_Aseprite,
        Buttons_Aseprite,
        Animator,
        AnimatorController,
        AnimatorAdditionalTag,
        AnimatorWithSlices,
        CharacterWithEmission,
        NineSlice_Aseprite,
        NineSlice_Data,
        ColorPalette,
    }
}
